package cs.otomasyon.dao.model;

// default package
// Generated 24.Ara.2013 00:08:55 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bolum generated by hbm2java
 */
@Entity
@Table(name = "bolum", catalog = "OtomasyonSistemi", uniqueConstraints = @UniqueConstraint(columnNames = "Ad"))
public class Bolum implements java.io.Serializable {

	private Integer id;
	private String ad;

	public Bolum() {
	}

	public Bolum(String ad) {
		this.ad = ad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Ad", unique = true, nullable = false)
	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

}
