package cs.otomasyon.dao.model;

// Generated 04.Ara.2013 23:49:21 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uye generated by hbm2java
 */
@Entity
@Table(name = "Uye", catalog = "OtomasyonSistemi")
public class Uye implements java.io.Serializable {

	private Integer uyeId;
	private String uyeAd;
	private String uyeSoyad;
	private String uyeOgrenciNo;
	private String uyeMailAdresi;
	private String uyeTelNo;
	private String uyeKayitTarih;
	private String uyeBolum;

	public Uye() {
	}

	public Uye(String uyeAd, String uyeSoyad, String uyeOgrenciNo,
			String uyeMailAdresi, String uyeKayitTarih, String uyeBolum) {
		this.uyeAd = uyeAd;
		this.uyeSoyad = uyeSoyad;
		this.uyeOgrenciNo = uyeOgrenciNo;
		this.uyeMailAdresi = uyeMailAdresi;
		this.uyeKayitTarih = uyeKayitTarih;
		this.uyeBolum = uyeBolum;
	}

	public Uye(String uyeAd, String uyeSoyad, String uyeOgrenciNo,
			String uyeMailAdresi, String uyeTelNo, String uyeKayitTarih,
			String uyeBolum) {
		this.uyeAd = uyeAd;
		this.uyeSoyad = uyeSoyad;
		this.uyeOgrenciNo = uyeOgrenciNo;
		this.uyeMailAdresi = uyeMailAdresi;
		this.uyeTelNo = uyeTelNo;
		this.uyeKayitTarih = uyeKayitTarih;
		this.uyeBolum = uyeBolum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "uyeID", unique = true, nullable = false)
	public Integer getUyeId() {
		return this.uyeId;
	}

	public void setUyeId(Integer uyeId) {
		this.uyeId = uyeId;
	}

	@Column(name = "uyeAd", nullable = false, length = 45)
	public String getUyeAd() {
		return this.uyeAd;
	}

	public void setUyeAd(String uyeAd) {
		this.uyeAd = uyeAd;
	}

	@Column(name = "uyeSoyad", nullable = false, length = 45)
	public String getUyeSoyad() {
		return this.uyeSoyad;
	}

	public void setUyeSoyad(String uyeSoyad) {
		this.uyeSoyad = uyeSoyad;
	}

	@Column(name = "uyeOgrenciNo", nullable = false, length = 45)
	public String getUyeOgrenciNo() {
		return this.uyeOgrenciNo;
	}

	public void setUyeOgrenciNo(String uyeOgrenciNo) {
		this.uyeOgrenciNo = uyeOgrenciNo;
	}

	@Column(name = "uyeMailAdresi", nullable = false, length = 45)
	public String getUyeMailAdresi() {
		return this.uyeMailAdresi;
	}

	public void setUyeMailAdresi(String uyeMailAdresi) {
		this.uyeMailAdresi = uyeMailAdresi;
	}

	@Column(name = "uyeTelNo", length = 45)
	public String getUyeTelNo() {
		return this.uyeTelNo;
	}

	public void setUyeTelNo(String uyeTelNo) {
		this.uyeTelNo = uyeTelNo;
	}

	@Column(name = "uyeKayitTarih", nullable = false, length = 45)
	public String getUyeKayitTarih() {
		return this.uyeKayitTarih;
	}

	public void setUyeKayitTarih(String uyeKayitTarih) {
		this.uyeKayitTarih = uyeKayitTarih;
	}

	@Column(name = "uyeBolum", nullable = false, length = 45)
	public String getUyeBolum() {
		return this.uyeBolum;
	}

	public void setUyeBolum(String uyeBolum) {
		this.uyeBolum = uyeBolum;
	}

}
