package cs.otomasyon.dao.model;

// default package
// Generated 24.Ara.2013 00:08:55 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uye generated by hbm2java
 */
@Entity
@Table(name = "Uye", catalog = "OtomasyonSistemi")
public class Uye implements java.io.Serializable {

	private Integer id;
	private String ad;
	private String soyad;
	private String ogrenciNo;
	private String mailAdresi;
	private String telNo;
	private String kayitTarih;
	private Integer bolumId;

	public Uye() {
	}

	public Uye(String ad, String soyad, String ogrenciNo, String mailAdresi,
			String kayitTarih) {
		this.ad = ad;
		this.soyad = soyad;
		this.ogrenciNo = ogrenciNo;
		this.mailAdresi = mailAdresi;
		this.kayitTarih = kayitTarih;
	}

	public Uye(String ad, String soyad, String ogrenciNo, String mailAdresi,
			String telNo, String kayitTarih, Integer bolumId) {
		this.ad = ad;
		this.soyad = soyad;
		this.ogrenciNo = ogrenciNo;
		this.mailAdresi = mailAdresi;
		this.telNo = telNo;
		this.kayitTarih = kayitTarih;
		this.bolumId = bolumId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Ad", nullable = false, length = 45)
	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	@Column(name = "Soyad", nullable = false, length = 45)
	public String getSoyad() {
		return this.soyad;
	}

	public void setSoyad(String soyad) {
		this.soyad = soyad;
	}

	@Column(name = "OgrenciNo", nullable = false, length = 45)
	public String getOgrenciNo() {
		return this.ogrenciNo;
	}

	public void setOgrenciNo(String ogrenciNo) {
		this.ogrenciNo = ogrenciNo;
	}

	@Column(name = "MailAdresi", nullable = false, length = 45)
	public String getMailAdresi() {
		return this.mailAdresi;
	}

	public void setMailAdresi(String mailAdresi) {
		this.mailAdresi = mailAdresi;
	}

	@Column(name = "TelNo", length = 45)
	public String getTelNo() {
		return this.telNo;
	}

	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	@Column(name = "KayitTarih", nullable = false, length = 45)
	public String getKayitTarih() {
		return this.kayitTarih;
	}

	public void setKayitTarih(String kayitTarih) {
		this.kayitTarih = kayitTarih;
	}

	@Column(name = "BolumId")
	public Integer getBolumId() {
		return this.bolumId;
	}

	public void setBolumId(Integer bolumId) {
		this.bolumId = bolumId;
	}

}
